const artForms = [
  {
    "id": 1,
    "name": "Madhubani Painting",
    "state": "Bihar",
    "location": "Madhubani",
    "latitude": 26.3533,
    "longitude": 86.0718,
    "category": "Painting",
    "shortDescription": "A traditional painting style from the Mithila region featuring geometric patterns.",
    "historicalContext": "Historically created by women on walls and floors during festivals and ceremonies.",
    "image": "https://placehold.co/600x400/f97316/ffffff?text=Madhubani%20Painting"
  },
  {
    "id": 2,
    "name": "Warli Painting",
    "state": "Maharashtra",
    "location": "Palghar",
    "latitude": 19.6967,
    "longitude": 72.7699,
    "category": "Painting",
    "shortDescription": "A tribal art form known for its rhythmic, geometric depiction of nature and daily life.",
    "historicalContext": "Created by the Warli tribe, primarily using white pigment made from rice paste.",
    "image": "https://placehold.co/600x400/f97316/ffffff?text=Warli%20Painting"
  },
  {
    "id": 3,
    "name": "Pattachitra",
    "state": "Odisha",
    "location": "Raghurajpur",
    "latitude": 19.8517,
    "longitude": 85.8115,
    "category": "Painting",
    "shortDescription": "Traditional cloth-based scroll painting known for intricate details and mythological narratives.",
    "historicalContext": "Closely tied to the cult of Shri Jagannath and the temple traditions of Puri.",
    "image": "https://upload.wikimedia.org/wikipedia/commons/7/7d/Odisha_Pattachitara_Depicting_Unconditional_Love_between_Radha_Krushna.jpg"
  },
  {
    "id": 4,
    "name": "Kalamkari",
    "state": "Andhra Pradesh",
    "location": "Machilipatnam",
    "latitude": 16.1793,
    "longitude": 81.1342,
    "category": "Textile",
    "shortDescription": "Hand-painted or block-printed cotton textile featuring intricate organic patterns.",
    "historicalContext": "Derived from 'kalam' (pen) and 'kari' (craftsmanship), flourishing under Islamic and Hindu rulers.",
    "image": "https://thumb.wikimedia.org/wikipedia/commons/thumb/f/ff/Kalamkari_painting_of_Lord_Vishnu_on_serpent_Ananta.jpg/960px-Kalamkari_painting_of_Lord_Vishnu_on_serpent_Ananta.jpg"
  },
  {
    "id": 5,
    "name": "Tanjore Painting",
    "state": "Tamil Nadu",
    "location": "Thanjavur",
    "latitude": 10.7867,
    "longitude": 79.1378,
    "category": "Painting",
    "shortDescription": "Classical South Indian painting style characterized by rich colors and gold foil work.",
    "historicalContext": "Originated during the Maratha period in the 16th century in the town of Thanjavur.",
    "image": "https://thumb.wikimedia.org/wikipedia/commons/thumb/f/fb/Thanjavur_art_from_south_India.jpg/960px-Thanjavur_art_from_south_India.jpg"
  },
  {
    "id": 6,
    "name": "Kathakali",
    "state": "Kerala",
    "location": "Kochi",
    "latitude": 9.9312,
    "longitude": 76.2673,
    "category": "Performing Arts",
    "shortDescription": "A major form of classical Indian dance known for elaborate makeup and costumes.",
    "historicalContext": "Originated in Kerala in the 17th century, combining devotion, drama, dance, and music.",
    "image": "https://thumb.wikimedia.org/wikipedia/commons/thumb/2/2c/Kathakali_-Play_with_Kaurava.jpg/960px-Kathakali_-Play_with_Kaurava.jpg"
  },
  {
    "id": 7,
    "name": "Phad Painting",
    "state": "Rajasthan",
    "location": "Bhilwara",
    "latitude": 25.3473,
    "longitude": 74.6369,
    "category": "Painting",
    "shortDescription": "A style of religious scroll painting and folk art created on a long piece of cloth.",
    "historicalContext": "Traditionally serves as a mobile temple for folk deities like Pabuji and Devnarayan.",
    "image": "https://placehold.co/600x400/f97316/ffffff?text=Phad%20Painting"
  },
  {
    "id": 8,
    "name": "Kalighat Painting",
    "state": "West Bengal",
    "location": "Kolkata",
    "latitude": 22.5726,
    "longitude": 88.3639,
    "category": "Painting",
    "shortDescription": "Characterized by sweeping brush strokes depicting gods and contemporary life.",
    "historicalContext": "Emerged in 19th-century Calcutta near the Kalighat Kali Temple as affordable souvenirs.",
    "image": "https://thumb.wikimedia.org/wikipedia/commons/thumb/0/0b/India%2C_Kalighat_painting%2C_19th_century_-_Two_Aspects_of_Kali-_Kali_Enshrined_-_1980.216.b_-_Cleveland_Museum_of_Art.jpg/960px-India%2C_Kalighat_painting%2C_19th_century_-_Two_Aspects_of_Kali-_Kali_Enshrined_-_1980.216.b_-_Cleveland_Museum_of_Art.jpg"
  },
  {
    "id": 9,
    "name": "Gond Art",
    "state": "Madhya Pradesh",
    "location": "Dindori",
    "latitude": 22.9511,
    "longitude": 81.0827,
    "category": "Painting",
    "shortDescription": "Tribal art using dots and lines to depict flora, fauna, and folklore.",
    "historicalContext": "Rooted in the belief that viewing good images brings good luck, practiced by the Gondi people.",
    "image": "https://placehold.co/600x400/f97316/ffffff?text=Gond%20Art"
  },
  {
    "id": 10,
    "name": "Kangra Painting",
    "state": "Himachal Pradesh",
    "location": "Kangra",
    "latitude": 32.0998,
    "longitude": 76.2691,
    "category": "Painting",
    "shortDescription": "Pahari painting style famous for its lyrical and romantic portrayal of themes.",
    "historicalContext": "Flourished under the patronage of Rajput rulers in the 18th century, focusing on Radha-Krishna.",
    "image": "https://thumb.wikimedia.org/wikipedia/commons/thumb/0/0c/Attributed_to_Khushala%2C_Indian%2C_active_late_18th_century_-_The_Gods_Sing_and_Dance_for_Shiva_and_Parvati_-_Google_Art_Project.jpg/960px-Attributed_to_Khushala%2C_Indian%2C_active_late_18th_century_-_The_Gods_Sing_and_Dance_for_Shiva_and_Parvati_-_Google_Art_Project.jpg"
  },
  {
    "id": 11,
    "name": "Papier-mâché",
    "state": "Jammu & Kashmir",
    "location": "Srinagar",
    "latitude": 34.0837,
    "longitude": 74.7973,
    "category": "Decorative Arts",
    "shortDescription": "Delicate decorative art created from paper pulp and beautifully painted.",
    "historicalContext": "Brought to Kashmir by a Persian mystic in the 15th century, influenced by Central Asian art.",
    "image": "https://placehold.co/600x400/f97316/ffffff?text=Papier-m%C3%A2ch%C3%A9"
  }
];